baseURL = 'https://xenonlanguage.github.io/'
languageCode = 'en-us'
title = 'Xenon Language'
theme = "terminal"
pagination.pagerSize = 5

[params]
  contentTypeName = "updates"

[markup.highlight]
noClasses = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Xenon"

    [languages.en.params]
      owner = "Liam Greenway"

      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Xenon"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"

        [[languages.en.menu.main]]
          identifier = "docs"
          name = "Docs"
          url = "/docs"